# Site settings
title: Welcome to<br>ADA for Warriors
email: info@swiftcryptollc.com
url: https://4ward.swiftcryptollc.com
description: >-
  A mission-driven single pool for Cardano that donates 50% of it's operator's rewards to the Third Option Foundation to help those who've quietly served.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'

# Footer settings
footer: Swift Crypto LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, twitter facebook stack-overflow, bitbucket, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Swift-Crypto-LLC
  - title: twitter
    url: https://twitter.com/mehen_cto
  - title: linkedin
    url: https://www.linkedin.com/company/swift-crypto-llc
  - title: telegram
    url: https://t.me/SwiftCryptoLLC
  - title: github
    url: https://github.com/swiftcryptollc
  - title: reddit
    url: https://www.reddit.com/user/SwiftCryptoLLC/

collections:
  news: 
    output: true
  missions: 
    output: true
  about:
    output: true
  community:
    output: true

# Build settings
markdown: kramdown
permalink: pretty